// Code generated by goyacc asn1.y. DO NOT EDIT.

//line asn1.y:3
package asn1go

import __yyfmt__ "fmt"

//line asn1.y:3

import (
	"fmt"
	"math"
)

//line asn1.y:15
type yySymType struct {
	yys        int
	name       string
	numberRepr string

	Number                            Number
	Real                              Real
	TagDefault                        int
	ExtensionDefault                  bool
	ModuleIdentifier                  ModuleIdentifier
	DefinitiveObjIdComponent          DefinitiveObjIdComponent
	DefinitiveObjIdComponentList      []DefinitiveObjIdComponent
	DefinitiveIdentifier              DefinitiveIdentifier
	Type                              Type
	ObjIdComponents                   ObjIdComponents
	DefinedValue                      DefinedValue
	ObjectIdentifierValue             ObjectIdentifierValue
	Value                             Value
	Assignment                        Assignment
	AssignmentList                    AssignmentList
	ModuleBody                        ModuleBody
	ValueReference                    ValueReference
	TypeReference                     TypeReference
	Constraint                        Constraint
	ConstraintSpec                    ConstraintSpec
	ElementSetSpec                    ElementSetSpec
	Unions                            Unions
	Intersections                     Intersections
	IntersectionElements              IntersectionElements
	Exclusions                        Exclusions
	Elements                          Elements
	SubtypeConstraint                 SubtypeConstraint
	RangeEndpoint                     RangeEndpoint
	NamedType                         NamedType
	ComponentType                     ComponentType
	ComponentTypeList                 ComponentTypeList
	SequenceType                      SequenceType
	Tag                               Tag
	Class                             int
	SequenceOfType                    SequenceOfType
	NamedBitList                      []NamedBit
	NamedBit                          NamedBit
	Imports                           []SymbolsFromModule
	SymbolsFromModule                 SymbolsFromModule
	SymbolList                        []Symbol
	Symbol                            Symbol
	GlobalModuleReference             GlobalModuleReference
	AlternativeTypeList               []NamedType
	ChoiceType                        ChoiceType
	ExtensionAdditionAlternative      ChoiceExtension
	ExtensionAdditionAlternativesList []ChoiceExtension
}

const WHITESPACE = 57346
const NEWLINE = 57347
const TYPEORMODULEREFERENCE = 57348
const VALUEIDENTIFIER = 57349
const NUMBER = 57350
const BSTRING = 57351
const XMLBSTRING = 57352
const HSTRING = 57353
const XMLHSTRING = 57354
const CSTRING = 57355
const XMLCSTRING = 57356
const ASSIGNMENT = 57357
const RANGE_SEPARATOR = 57358
const ELLIPSIS = 57359
const LEFT_VERSION_BRACKETS = 57360
const RIGHT_VERSION_BRACKETS = 57361
const XML_END_TAG_START = 57362
const XML_SINGLE_START_END = 57363
const XML_BOOLEAN_TRUE = 57364
const XML_BOOLEAN_FALSE = 57365
const XMLASN1TYPENAME = 57366
const EXPONENT = 57367
const OPEN_CURLY = 57368
const CLOSE_CURLY = 57369
const LESS = 57370
const GREATER = 57371
const COMMA = 57372
const DOT = 57373
const OPEN_ROUND = 57374
const CLOSE_ROUND = 57375
const OPEN_SQUARE = 57376
const CLOSE_SQUARE = 57377
const MINUS = 57378
const COLON = 57379
const EQUALS = 57380
const QUOTATION_MARK = 57381
const APOSTROPHE = 57382
const SPACE = 57383
const SEMICOLON = 57384
const AT = 57385
const PIPE = 57386
const EXCLAMATION = 57387
const CARET = 57388
const ABSENT = 57389
const ENCODED = 57390
const INTEGER = 57391
const RELATIVE_OID = 57392
const ABSTRACT_SYNTAX = 57393
const END = 57394
const INTERSECTION = 57395
const SEQUENCE = 57396
const ALL = 57397
const ENUMERATED = 57398
const ISO646String = 57399
const SET = 57400
const APPLICATION = 57401
const EXCEPT = 57402
const MAX = 57403
const SIZE = 57404
const AUTOMATIC = 57405
const EXPLICIT = 57406
const MIN = 57407
const STRING = 57408
const BEGIN = 57409
const EXPORTS = 57410
const MINUS_INFINITY = 57411
const SYNTAX = 57412
const BIT = 57413
const EXTENSIBILITY = 57414
const NULL = 57415
const T61String = 57416
const BMPString = 57417
const EXTERNAL = 57418
const NumericString = 57419
const TAGS = 57420
const BOOLEAN = 57421
const FALSE = 57422
const OBJECT = 57423
const TeletexString = 57424
const BY = 57425
const FROM = 57426
const ObjectDescriptor = 57427
const TRUE = 57428
const CHARACTER = 57429
const GeneralizedTime = 57430
const OCTET = 57431
const TYPE_IDENTIFIER = 57432
const CHOICE = 57433
const GeneralString = 57434
const OF = 57435
const UNION = 57436
const CLASS = 57437
const GraphicString = 57438
const OPTIONAL = 57439
const UNIQUE = 57440
const COMPONENT = 57441
const IA5String = 57442
const PATTERN = 57443
const UNIVERSAL = 57444
const COMPONENTS = 57445
const IDENTIFIER = 57446
const PDV = 57447
const UniversalString = 57448
const CONSTRAINED = 57449
const IMPLICIT = 57450
const PLUS_INFINITY = 57451
const UTCTime = 57452
const CONTAINING = 57453
const IMPLIED = 57454
const PRESENT = 57455
const UTF8String = 57456
const DEFAULT = 57457
const IMPORTS = 57458
const PrintableString = 57459
const VideotexString = 57460
const DEFINITIONS = 57461
const INCLUDES = 57462
const PRIVATE = 57463
const VisibleString = 57464
const EMBEDDED = 57465
const INSTANCE = 57466
const REAL = 57467
const WITH = 57468
const ANY = 57469
const DEFINED = 57470

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"WHITESPACE",
	"NEWLINE",
	"TYPEORMODULEREFERENCE",
	"VALUEIDENTIFIER",
	"NUMBER",
	"BSTRING",
	"XMLBSTRING",
	"HSTRING",
	"XMLHSTRING",
	"CSTRING",
	"XMLCSTRING",
	"ASSIGNMENT",
	"RANGE_SEPARATOR",
	"ELLIPSIS",
	"LEFT_VERSION_BRACKETS",
	"RIGHT_VERSION_BRACKETS",
	"XML_END_TAG_START",
	"XML_SINGLE_START_END",
	"XML_BOOLEAN_TRUE",
	"XML_BOOLEAN_FALSE",
	"XMLASN1TYPENAME",
	"EXPONENT",
	"OPEN_CURLY",
	"CLOSE_CURLY",
	"LESS",
	"GREATER",
	"COMMA",
	"DOT",
	"OPEN_ROUND",
	"CLOSE_ROUND",
	"OPEN_SQUARE",
	"CLOSE_SQUARE",
	"MINUS",
	"COLON",
	"EQUALS",
	"QUOTATION_MARK",
	"APOSTROPHE",
	"SPACE",
	"SEMICOLON",
	"AT",
	"PIPE",
	"EXCLAMATION",
	"CARET",
	"ABSENT",
	"ENCODED",
	"INTEGER",
	"RELATIVE_OID",
	"ABSTRACT_SYNTAX",
	"END",
	"INTERSECTION",
	"SEQUENCE",
	"ALL",
	"ENUMERATED",
	"ISO646String",
	"SET",
	"APPLICATION",
	"EXCEPT",
	"MAX",
	"SIZE",
	"AUTOMATIC",
	"EXPLICIT",
	"MIN",
	"STRING",
	"BEGIN",
	"EXPORTS",
	"MINUS_INFINITY",
	"SYNTAX",
	"BIT",
	"EXTENSIBILITY",
	"NULL",
	"T61String",
	"BMPString",
	"EXTERNAL",
	"NumericString",
	"TAGS",
	"BOOLEAN",
	"FALSE",
	"OBJECT",
	"TeletexString",
	"BY",
	"FROM",
	"ObjectDescriptor",
	"TRUE",
	"CHARACTER",
	"GeneralizedTime",
	"OCTET",
	"TYPE_IDENTIFIER",
	"CHOICE",
	"GeneralString",
	"OF",
	"UNION",
	"CLASS",
	"GraphicString",
	"OPTIONAL",
	"UNIQUE",
	"COMPONENT",
	"IA5String",
	"PATTERN",
	"UNIVERSAL",
	"COMPONENTS",
	"IDENTIFIER",
	"PDV",
	"UniversalString",
	"CONSTRAINED",
	"IMPLICIT",
	"PLUS_INFINITY",
	"UTCTime",
	"CONTAINING",
	"IMPLIED",
	"PRESENT",
	"UTF8String",
	"DEFAULT",
	"IMPORTS",
	"PrintableString",
	"VideotexString",
	"DEFINITIONS",
	"INCLUDES",
	"PRIVATE",
	"VisibleString",
	"EMBEDDED",
	"INSTANCE",
	"REAL",
	"WITH",
	"ANY",
	"DEFINED",
	"\"t\"",
	"\"o\"",
	"\"d\"",
	"\",\"",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line asn1.y:1055

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 31,
	52, 24,
	-2, 27,
	-1, 178,
	44, 235,
	94, 235,
	-2, 231,
	-1, 180,
	46, 238,
	53, 238,
	-2, 233,
	-1, 184,
	60, 241,
	-2, 239,
	-1, 193,
	16, 260,
	28, 260,
	-2, 254,
	-1, 325,
	46, 238,
	53, 238,
	-2, 234,
}

const yyPrivate = 57344

const yyLast = 912

var yyAct = [...]int16{
	203, 393, 206, 220, 365, 286, 127, 313, 17, 193,
	177, 238, 329, 309, 17, 257, 275, 249, 219, 208,
	214, 182, 163, 260, 170, 180, 245, 184, 159, 215,
	339, 355, 321, 19, 252, 377, 240, 252, 306, 165,
	144, 45, 3, 151, 5, 291, 19, 168, 38, 19,
	168, 400, 29, 11, 9, 133, 140, 271, 19, 168,
	322, 272, 128, 292, 263, 165, 19, 330, 165, 293,
	233, 19, 190, 19, 135, 169, 232, 165, 169, 225,
	128, 216, 224, 216, 62, 234, 150, 169, 24, 23,
	22, 227, 139, 213, 21, 35, 42, 148, 10, 31,
	332, 401, 134, 332, 129, 152, 137, 142, 172, 261,
	139, 172, 36, 58, 264, 47, 48, 399, 258, 162,
	172, 121, 162, 141, 50, 161, 61, 164, 161, 164,
	60, 162, 209, 212, 202, 340, 155, 161, 123, 103,
	223, 136, 241, 266, 390, 231, 226, 305, 171, 46,
	267, 171, 211, 241, 314, 241, 59, 241, 241, 124,
	171, 228, 221, 239, 40, 154, 251, 221, 244, 221,
	229, 122, 138, 143, 63, 44, 195, 53, 44, 246,
	128, 128, 315, 243, 389, 361, 378, 54, 164, 53,
	376, 375, 41, 327, 256, 316, 126, 44, 269, 54,
	276, 32, 44, 341, 254, 311, 283, 27, 402, 268,
	253, 284, 395, 128, 285, 287, 385, 384, 373, 363,
	290, 282, 281, 278, 259, 62, 273, 15, 295, 297,
	405, 65, 289, 383, 298, 304, 301, 303, 356, 354,
	349, 125, 307, 299, 288, 280, 277, 251, 251, 25,
	338, 199, 132, 131, 130, 30, 7, 359, 19, 19,
	350, 344, 164, 164, 323, 270, 164, 362, 366, 216,
	64, 164, 319, 308, 310, 28, 248, 12, 334, 145,
	331, 318, 343, 209, 14, 345, 212, 326, 325, 324,
	14, 26, 360, 164, 19, 18, 312, 347, 255, 342,
	47, 48, 352, 55, 48, 348, 346, 18, 19, 351,
	4, 317, 398, 222, 387, 386, 367, 337, 230, 336,
	335, 333, 265, 235, 236, 358, 262, 207, 403, 357,
	205, 164, 204, 210, 39, 34, 1, 392, 372, 368,
	331, 276, 201, 364, 200, 72, 153, 242, 43, 57,
	56, 37, 274, 370, 69, 371, 77, 369, 86, 149,
	374, 237, 164, 102, 164, 84, 217, 379, 218, 82,
	81, 380, 80, 79, 382, 388, 67, 394, 391, 85,
	279, 91, 90, 71, 197, 368, 368, 328, 194, 396,
	397, 55, 19, 168, 192, 191, 209, 186, 404, 189,
	188, 294, 296, 185, 406, 183, 394, 181, 178, 300,
	302, 165, 381, 176, 175, 174, 173, 187, 87, 120,
	68, 169, 33, 49, 51, 52, 167, 166, 157, 160,
	78, 158, 156, 250, 94, 320, 247, 83, 73, 99,
	179, 93, 110, 100, 75, 66, 70, 139, 74, 76,
	198, 6, 16, 13, 172, 2, 88, 8, 95, 114,
	106, 20, 111, 0, 89, 162, 96, 113, 0, 0,
	353, 161, 119, 104, 97, 0, 92, 107, 55, 19,
	168, 108, 0, 0, 0, 109, 0, 0, 0, 0,
	0, 115, 0, 0, 171, 105, 0, 0, 165, 116,
	0, 0, 112, 117, 187, 0, 120, 118, 169, 0,
	98, 196, 101, 0, 0, 0, 0, 0, 0, 0,
	0, 94, 0, 0, 0, 0, 99, 0, 93, 110,
	100, 0, 0, 0, 139, 0, 0, 198, 0, 0,
	0, 172, 0, 88, 0, 95, 114, 106, 0, 111,
	0, 89, 162, 96, 113, 0, 0, 0, 161, 119,
	104, 97, 0, 92, 107, 55, 0, 321, 108, 0,
	0, 0, 109, 0, 0, 0, 0, 0, 115, 0,
	0, 171, 105, 0, 0, 0, 116, 0, 0, 112,
	117, 0, 0, 120, 118, 322, 0, 98, 196, 101,
	0, 0, 0, 0, 0, 0, 0, 0, 94, 0,
	0, 0, 0, 99, 0, 93, 110, 100, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	88, 0, 95, 114, 106, 0, 111, 0, 89, 55,
	96, 113, 0, 0, 0, 0, 119, 104, 97, 0,
	92, 107, 0, 0, 0, 108, 0, 0, 0, 109,
	0, 0, 0, 0, 0, 115, 0, 120, 0, 105,
	0, 0, 0, 116, 0, 0, 112, 117, 0, 0,
	0, 118, 94, 0, 98, 0, 101, 99, 241, 93,
	110, 100, 0, 0, 0, 0, 0, 147, 0, 0,
	0, 0, 0, 0, 88, 0, 95, 114, 106, 0,
	111, 0, 89, 0, 96, 113, 55, 19, 0, 0,
	119, 104, 97, 0, 92, 107, 0, 0, 0, 108,
	0, 0, 0, 109, 0, 0, 0, 0, 0, 115,
	0, 146, 0, 105, 120, 0, 0, 116, 0, 0,
	112, 117, 0, 0, 0, 118, 0, 0, 98, 94,
	101, 0, 0, 0, 99, 0, 93, 110, 100, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 88, 0, 95, 114, 106, 0, 111, 0, 89,
	55, 96, 113, 0, 0, 0, 0, 119, 104, 97,
	0, 92, 107, 0, 0, 0, 108, 0, 0, 0,
	109, 0, 0, 0, 0, 0, 115, 0, 120, 0,
	105, 0, 0, 0, 116, 0, 0, 112, 117, 0,
	0, 0, 118, 94, 0, 98, 0, 101, 99, 0,
	93, 110, 100, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 88, 0, 95, 114, 106,
	0, 111, 0, 89, 0, 96, 113, 0, 0, 0,
	0, 119, 104, 97, 0, 92, 107, 0, 0, 0,
	108, 0, 0, 0, 109, 0, 0, 0, 0, 0,
	115, 0, 0, 0, 105, 0, 0, 0, 116, 0,
	0, 112, 117, 0, 0, 0, 118, 0, 0, 98,
	0, 101,
}

var yyPact = [...]int16{
	304, -1000, -75, 230, -1000, -10, -1000, 287, 22, 12,
	11, 10, 222, 287, -1000, -1000, -1000, 175, -1000, -1000,
	260, -60, -1000, -1000, -1000, -1000, -1000, 299, 32, -1000,
	168, 27, -1000, 60, -68, 109, -1000, 297, 294, 88,
	84, 195, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 297,
	-1000, -1000, -1000, 255, 784, -1000, 79, 294, -1000, 54,
	-1000, -1000, 294, -1000, 784, 181, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 38, -1000,
	-1000, -1000, 228, 227, 226, -1000, -49, 36, -1000, 48,
	30, -88, 633, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 31,
	-16, -1000, -1000, 304, -1000, 149, 51, -1000, 385, 225,
	301, 301, 301, -1000, -1000, 66, 710, -11, -14, 149,
	64, 710, -17, -23, 2, 149, 784, 784, -1000, 28,
	-1000, -1000, -1000, -1000, 13, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 26, -1000, -1000, 179, 290,
	-1000, -1000, -1000, 73, -1000, -1000, 194, -1000, -1000, 49,
	-1000, 20, -1000, 97, -1000, 49, -1000, 385, -1000, -1000,
	-1000, -1000, -1000, -1000, 249, 149, -42, 198, -1000, 301,
	219, 193, -1000, 784, 218, 192, -1000, 191, -1000, 174,
	184, -1000, 174, -1000, 185, 217, 73, -1000, 190, -1000,
	-52, -24, 149, -1000, 710, 710, -1000, -1000, 185, 216,
	149, -1000, 710, 710, 301, 149, 149, 112, -1000, -1000,
	-1000, -92, -1000, -1000, -1000, 215, 26, 26, -1000, -1000,
	-1000, 173, -1000, 288, 146, 179, -1000, 162, 559, 247,
	-1000, 472, 472, -1000, -1000, 472, -1000, -1000, -1000, 160,
	39, 149, 224, -1000, 3, -1000, 171, -1000, 252, 149,
	-1000, 244, 301, 24, -1000, 301, 213, 243, -1000, -1000,
	59, -1000, 51, 784, 149, -1000, 149, -1000, 212, -1000,
	149, -1000, 149, -1000, -1000, -1000, -100, -1000, 211, -1000,
	-1000, 29, 232, -1000, -1000, 284, -1000, -1000, -1000, -1000,
	148, -1000, 259, 189, -1000, -1000, -1000, -1000, -1000, -1000,
	42, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 251, -1000,
	301, 28, 188, -1000, 73, -1000, 158, 157, -1000, -1000,
	-1000, -1000, -1000, 149, -1000, -95, -1000, 153, -1000, 146,
	-1000, 51, -1000, 385, -1000, 206, 187, 186, 149, -1000,
	151, 111, 185, 301, 182, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 301, 301, -1000, 4, -1000, -1000,
	-1000, -1000, 178, -1000, -1000, 301, 203, -1000, -1000, -1000,
	-1000, -1000, 301, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 24, 7, 41, 139, 0, 461, 457, 455, 453,
	227, 277, 452, 451, 276, 13, 449, 448, 446, 445,
	176, 444, 438, 437, 3, 436, 17, 433, 26, 28,
	432, 9, 431, 430, 429, 428, 427, 426, 22, 11,
	124, 425, 424, 423, 422, 149, 420, 418, 6, 416,
	415, 414, 413, 412, 10, 408, 407, 25, 405, 21,
	23, 27, 403, 400, 399, 397, 395, 394, 72, 388,
	387, 384, 12, 383, 382, 381, 379, 376, 373, 372,
	370, 369, 18, 368, 366, 29, 365, 363, 361, 359,
	358, 356, 354, 352, 16, 351, 350, 349, 113, 156,
	96, 348, 347, 346, 345, 344, 342, 342, 1, 338,
	337, 336, 335, 334, 333, 19, 332, 330, 15, 328,
	2, 327, 20, 5, 327, 327, 327, 327, 327, 327,
	327, 326, 322, 321, 320, 319, 317, 4, 316, 315,
	314, 312, 311,
}

var yyR1 = [...]uint8{
	0, 111, 4, 3, 45, 39, 5, 8, 13, 13,
	11, 11, 9, 9, 9, 10, 12, 7, 7, 7,
	7, 6, 6, 44, 44, 112, 112, 112, 113, 113,
	95, 95, 96, 96, 97, 97, 98, 103, 102, 102,
	102, 99, 99, 100, 101, 101, 101, 43, 43, 40,
	40, 76, 15, 42, 41, 20, 20, 20, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 77, 77, 24, 31, 30, 30,
	30, 30, 18, 35, 35, 17, 17, 114, 114, 115,
	115, 38, 38, 32, 32, 22, 116, 116, 116, 117,
	119, 120, 120, 121, 121, 33, 34, 34, 36, 36,
	37, 37, 1, 1, 1, 1, 2, 2, 92, 92,
	93, 93, 94, 94, 91, 21, 78, 78, 78, 122,
	122, 123, 123, 85, 84, 124, 125, 125, 126, 126,
	127, 127, 128, 129, 129, 83, 83, 82, 82, 82,
	82, 80, 80, 80, 81, 81, 23, 23, 104, 105,
	105, 107, 109, 109, 110, 110, 108, 130, 106, 106,
	86, 86, 86, 87, 88, 88, 89, 89, 89, 89,
	79, 79, 16, 29, 29, 28, 28, 25, 25, 25,
	25, 26, 26, 27, 14, 73, 73, 74, 74, 74,
	74, 74, 74, 74, 74, 74, 74, 74, 74, 74,
	75, 90, 90, 46, 46, 47, 47, 47, 47, 47,
	47, 47, 47, 48, 49, 50, 51, 51, 51, 52,
	53, 54, 54, 55, 55, 56, 57, 57, 58, 59,
	59, 62, 60, 131, 131, 132, 132, 61, 61, 65,
	65, 65, 65, 65, 63, 64, 69, 69, 70, 70,
	71, 71, 72, 72, 68, 66, 67, 67, 133, 134,
	134, 135, 136, 137, 137, 138, 139, 140, 140, 141,
	141, 141, 141, 118, 118, 142, 142, 142,
}

var yyR2 = [...]int8{
	0, 8, 1, 1, 1, 1, 1, 2, 3, 0,
	1, 2, 1, 1, 1, 1, 4, 2, 2, 2,
	0, 2, 0, 3, 0, 3, 3, 0, 1, 0,
	3, 0, 1, 0, 1, 2, 3, 2, 1, 1,
	0, 1, 3, 1, 1, 1, 1, 1, 2, 1,
	1, 1, 4, 3, 4, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 4, 1, 3, 4,
	4, 1, 2, 1, 1, 4, 1, 4, 6, 1,
	1, 1, 3, 1, 1, 1, 1, 1, 1, 2,
	1, 1, 1, 3, 5, 3, 1, 2, 2, 5,
	1, 3, 4, 4, 2, 1, 3, 5, 4, 1,
	2, 2, 0, 1, 1, 2, 2, 0, 1, 3,
	1, 1, 4, 0, 2, 1, 3, 1, 2, 3,
	3, 3, 5, 4, 3, 3, 1, 4, 4, 5,
	1, 1, 2, 0, 1, 3, 1, 4, 1, 3,
	2, 3, 3, 4, 1, 1, 1, 1, 1, 0,
	3, 3, 2, 3, 4, 1, 2, 1, 1, 1,
	1, 1, 1, 4, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	2, 1, 1, 2, 1, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 1, 1, 1, 3, 5, 1,
	1, 1, 2, 1, 3, 1, 1, 3, 1, 1,
	2, 1, 2, 1, 1, 1, 1, 1, 3, 1,
	1, 1, 1, 1, 1, 3, 1, 2, 1, 2,
	1, 1, 1, 1, 2, 1, 3, 3, 1, 1,
	1, 3, 5, 1, 3, 2, 2, 1, 0, 1,
	1, 1, 0, 2, 0, 1, 1, 3,
}

var yyChk = [...]int16{
	-1000, -111, -8, -3, 6, 119, -13, 26, -7, 64,
	108, 63, -11, -9, -14, -10, -12, -5, 8, 7,
	-6, 72, 78, 78, 78, 27, -11, 32, 15, 112,
	-10, 67, 33, -44, -112, 68, 52, -95, 116, -113,
	55, -99, -100, -101, -4, -3, -45, 6, 7, -43,
	-40, -42, -41, -4, -45, 6, -96, -97, -98, -99,
	42, 42, 30, -40, 15, -20, -19, -77, -46, -92,
	-18, -73, -104, -22, -17, -21, -16, -91, -33, -78,
	-79, -80, -81, -23, -86, -76, -90, -47, 71, 79,
	-74, -75, 91, 56, 49, 73, 81, 89, 125, 54,
	58, 127, -87, -4, 88, 110, 75, 92, 96, 100,
	57, 77, 117, 82, 74, 106, 114, 118, 122, 87,
	34, 42, -98, 84, -100, -20, 15, -48, 32, 66,
	26, 26, 26, 104, 66, 26, 93, -48, -68, 62,
	26, 93, -48, -68, 128, -20, 108, 64, 66, -89,
	102, 59, 121, -103, -3, -31, -30, -35, -32, -29,
	-34, 86, 80, -38, -5, 26, -36, -37, 8, 36,
	-1, 109, 69, -49, -50, -51, -52, -54, -55, 55,
	-57, -56, -59, -58, -61, -62, -65, 32, -63, -64,
	-68, -66, -67, -31, -69, -20, 126, -71, 65, 26,
	-105, -106, -24, -5, -116, -117, -120, -121, -115, -5,
	-114, -115, -5, 27, -122, -85, 17, -84, -83, -82,
	-24, 103, -20, -24, 93, 93, -48, 27, -122, -85,
	-20, -24, 93, 93, 83, -20, -20, -88, -39, -15,
	8, 129, -102, -29, -15, -28, -15, -25, -14, -26,
	-27, -5, 8, 31, 25, 8, -1, -118, 45, 30,
	-60, 60, -131, 44, 94, -132, 46, 53, -60, -54,
	16, 99, 103, 28, -93, -94, -5, 27, 30, -20,
	27, 30, 30, 32, 27, 30, -123, 30, 27, -118,
	30, 97, 115, 93, -20, -24, -20, -24, -123, 27,
	-20, -24, -20, -24, -5, 35, 130, 27, -28, -15,
	-28, 32, 8, -2, 8, 36, 33, -142, -38, -15,
	-20, 8, 36, 17, -61, -57, -59, 33, -70, -72,
	28, -31, 61, -133, -48, -134, -135, -136, 26, 27,
	132, 32, -122, -24, 17, -120, -38, -15, -115, 27,
	17, -82, -31, -20, 27, 131, 27, -26, -15, 25,
	8, 37, 8, 30, -72, -137, 17, -138, -5, -94,
	-39, -15, -109, 30, -118, 33, 33, 130, 33, -2,
	-31, -53, -54, 27, 30, 30, -139, -140, -48, 33,
	33, -123, -110, -108, -24, 30, -137, -137, -141, 113,
	47, 97, 30, -119, -120, 27, -108,
}

var yyDef = [...]int16{
	0, -2, 0, 9, 3, 20, 7, 0, 22, 0,
	0, 0, 0, 10, 12, 13, 14, 194, 15, 6,
	0, 0, 17, 18, 19, 8, 11, 0, 0, 21,
	0, -2, 16, 0, 31, 29, 1, 0, 33, 0,
	0, 28, 41, 43, 44, 45, 46, 2, 4, 23,
	47, 49, 50, 0, 0, 2, 0, 32, 34, 0,
	25, 26, 0, 48, 0, 0, 55, 56, 57, 58,
	59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
	69, 70, 71, 72, 73, 74, 75, 214, 0, 82,
	195, 196, 0, 0, 85, 125, 0, 0, 105, 0,
	0, 156, 0, 51, 211, 212, 197, 198, 199, 200,
	201, 202, 203, 204, 205, 206, 207, 208, 209, 0,
	179, 30, 35, 0, 42, 53, 0, 213, 0, 118,
	0, 0, 0, 182, 124, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 170, 0, 0, 210, 0,
	176, 177, 178, 36, 40, 54, 77, 78, 79, 80,
	81, 83, 84, 93, 94, 0, 106, 107, 91, 0,
	108, 110, 111, 284, 224, 225, 226, 229, -2, 0,
	-2, 0, 236, 0, -2, 0, 247, 0, 249, 250,
	251, 252, 253, -2, 0, 265, 0, 256, 261, 0,
	0, 160, 168, 0, 0, 96, 99, 101, 103, 104,
	0, 87, 0, 126, 132, 0, 129, 133, 134, 145,
	147, 0, 180, 181, 0, 0, 264, 151, 132, 0,
	154, 155, 0, 0, 0, 171, 172, 0, 174, 175,
	5, 0, 37, 38, 39, 0, 190, 185, 187, 188,
	189, 194, 191, 0, 0, 92, 109, 0, 0, 0,
	232, 0, 0, 243, 244, 0, 245, 246, 240, 0,
	0, 0, 0, 257, 0, 120, 0, 158, 0, 76,
	95, 0, 0, 0, 86, 0, 0, 0, 128, 130,
	0, 148, 0, 0, 217, 221, 218, 222, 0, 153,
	215, 219, 216, 220, 157, 173, 0, 183, 0, 190,
	186, 0, 113, 115, 116, 0, 223, 283, 285, 286,
	0, 91, 0, 227, 242, -2, 237, 248, 255, 258,
	0, 262, 263, 266, 268, 267, 269, 270, 0, 119,
	0, 0, 163, 169, 284, 102, 0, 0, 88, 127,
	131, 146, 149, 150, 152, 0, 184, 0, 192, 0,
	117, 0, 92, 0, 259, 0, 0, 273, 278, 121,
	0, 0, 132, 0, 97, 89, 90, 52, 193, 114,
	287, 228, 230, 271, 0, 0, 275, 282, 277, 122,
	123, 159, 162, 164, 166, 0, 0, 274, 276, 279,
	280, 281, 0, 98, 100, 272, 165,
}

var yyTok1 = [...]uint8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 132, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	131, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 130, 3, 3, 3, 3, 129,
}

var yyTok2 = [...]uint8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
	122, 123, 124, 125, 126, 127, 128,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-8 : yypt+1]
//line asn1.y:330
		{
			yylex.(*MyLexer).result = &ModuleDefinition{ModuleIdentifier: yyDollar[1].ModuleIdentifier, TagDefault: yyDollar[3].TagDefault, ExtensibilityImplied: yyDollar[4].ExtensionDefault, ModuleBody: yyDollar[7].ModuleBody}
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:333
		{
			yyVAL.TypeReference = TypeReference(yyDollar[1].name)
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:338
		{
			yyVAL.ValueReference = ValueReference(yyDollar[1].name)
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:349
		{
			yyVAL.ModuleIdentifier = ModuleIdentifier{Reference: yyDollar[1].name, DefinitiveIdentifier: yyDollar[2].DefinitiveIdentifier}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:352
		{
			yyVAL.DefinitiveIdentifier = DefinitiveIdentifier(yyDollar[2].DefinitiveObjIdComponentList)
		}
	case 9:
		yyDollar = yyS[yypt-0 : yypt+1]
//line asn1.y:353
		{
			yyVAL.DefinitiveIdentifier = DefinitiveIdentifier(make([]DefinitiveObjIdComponent, 0))
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:356
		{
			yyVAL.DefinitiveObjIdComponentList = append(make([]DefinitiveObjIdComponent, 0), yyDollar[1].DefinitiveObjIdComponent)
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:357
		{
			yyVAL.DefinitiveObjIdComponentList = append(append(make([]DefinitiveObjIdComponent, 0), yyDollar[1].DefinitiveObjIdComponent), yyDollar[2].DefinitiveObjIdComponentList...)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:360
		{
			yyVAL.DefinitiveObjIdComponent = DefinitiveObjIdComponent{Name: yyDollar[1].name}
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:361
		{
			yyVAL.DefinitiveObjIdComponent = DefinitiveObjIdComponent{Id: yyDollar[1].Number.IntValue()}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:362
		{
			yyVAL.DefinitiveObjIdComponent = yyDollar[1].DefinitiveObjIdComponent
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:365
		{
			yyVAL.Number = yyDollar[1].Number
		}
	case 16:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:369
		{
			yyVAL.DefinitiveObjIdComponent = DefinitiveObjIdComponent{Name: yyDollar[1].name, Id: yyDollar[3].Number.IntValue()}
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:372
		{
			yyVAL.TagDefault = TAGS_EXPLICIT
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:373
		{
			yyVAL.TagDefault = TAGS_IMPLICIT
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:374
		{
			yyVAL.TagDefault = TAGS_AUTOMATIC
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line asn1.y:375
		{
			yyVAL.TagDefault = TAGS_EXPLICIT
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:378
		{
			yyVAL.ExtensionDefault = true
		}
	case 22:
		yyDollar = yyS[yypt-0 : yypt+1]
//line asn1.y:379
		{
			yyVAL.ExtensionDefault = false
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:382
		{
			yyVAL.ModuleBody = ModuleBody{Imports: yyDollar[2].Imports, AssignmentList: yyDollar[3].AssignmentList}
		}
	case 24:
		yyDollar = yyS[yypt-0 : yypt+1]
//line asn1.y:383
		{
			yyVAL.ModuleBody = ModuleBody{}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:396
		{
			yyVAL.Imports = yyDollar[2].Imports
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
//line asn1.y:397
		{
			yyVAL.Imports = make([]SymbolsFromModule, 0)
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:400
		{
			yyVAL.Imports = yyDollar[1].Imports
		}
	case 33:
		yyDollar = yyS[yypt-0 : yypt+1]
//line asn1.y:401
		{
			yyVAL.Imports = make([]SymbolsFromModule, 0)
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:404
		{
			yyVAL.Imports = append(make([]SymbolsFromModule, 0), yyDollar[1].SymbolsFromModule)
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:405
		{
			yyVAL.Imports = append(yyDollar[1].Imports, yyDollar[2].SymbolsFromModule)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:408
		{
			yyVAL.SymbolsFromModule = SymbolsFromModule{yyDollar[1].SymbolList, yyDollar[3].GlobalModuleReference}
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:411
		{
			yyVAL.GlobalModuleReference = GlobalModuleReference{yyDollar[1].name, yyDollar[2].Value}
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:414
		{
			yyVAL.Value = yyDollar[1].ObjectIdentifierValue
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:415
		{
			yyVAL.Value = yyDollar[1].DefinedValue
		}
	case 40:
		yyDollar = yyS[yypt-0 : yypt+1]
//line asn1.y:416
		{
			yyVAL.Value = nil
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:419
		{
			yyVAL.SymbolList = append(make([]Symbol, 0), yyDollar[1].Symbol)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:420
		{
			yyVAL.SymbolList = append(yyDollar[1].SymbolList, yyDollar[3].Symbol)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:427
		{
			yyVAL.Symbol = TypeReference(yyDollar[1].TypeReference)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:428
		{
			yyVAL.Symbol = ModuleReference(yyDollar[1].name)
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:429
		{
			yyVAL.Symbol = ValueReference(yyDollar[1].ValueReference)
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:435
		{
			yyVAL.AssignmentList = NewAssignmentList(yyDollar[1].Assignment)
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:436
		{
			yyVAL.AssignmentList = yyDollar[1].AssignmentList.Append(yyDollar[2].Assignment)
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:452
		{
			yyVAL.Type = yyDollar[1].TypeReference
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:459
		{
			yyVAL.DefinedValue = DefinedValue{}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:467
		{
			yyVAL.Assignment = TypeAssignment{yyDollar[1].TypeReference, yyDollar[3].Type}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:470
		{
			yyVAL.Assignment = ValueAssignment{yyDollar[1].ValueReference, yyDollar[2].Type, yyDollar[4].Value}
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:517
		{
			yyVAL.NamedType = NamedType{Identifier: Identifier(yyDollar[1].name), Type: yyDollar[2].Type}
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:540
		{
			yyVAL.Value = yyDollar[1].ObjectIdentifierValue
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:553
		{
			yyVAL.Type = BooleanType{}
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:556
		{
			yyVAL.Value = Boolean(true)
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:557
		{
			yyVAL.Value = Boolean(false)
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:562
		{
			yyVAL.Type = IntegerType{}
		}
	case 86:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:563
		{
			yyVAL.Type = IntegerType{}
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:574
		{
			yyVAL.Number = yyDollar[1].Number
		}
	case 92:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:575
		{
			yyVAL.Number = yyDollar[2].Number.UnaryMinus()
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:580
		{
			yyVAL.Value = yyDollar[1].Number
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:581
		{
			yyVAL.Value = IdentifiedIntegerValue{Name: yyDollar[1].name}
		}
	case 95:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:586
		{
			yyVAL.Type = EnumeratedType{}
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:609
		{
			yyVAL.Type = RealType{}
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:618
		{
			yyVAL.Value = yyDollar[1].Real
		}
	case 109:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:619
		{
			yyVAL.Value = yyDollar[2].Real.UnaryMinus()
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:623
		{
			yyVAL.Value = Real(math.Inf(1))
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:624
		{
			yyVAL.Value = Real(math.Inf(-1))
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:628
		{
			yyVAL.Real = parseRealNumber(yyDollar[1].Number, 0, 0)
		}
	case 113:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:629
		{
			yyVAL.Real = parseRealNumber(yyDollar[1].Number, yyDollar[3].Number, 0)
		}
	case 114:
		yyDollar = yyS[yypt-5 : yypt+1]
//line asn1.y:630
		{
			yyVAL.Real = parseRealNumber(yyDollar[1].Number, yyDollar[3].Number, yyDollar[5].Number)
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:631
		{
			yyVAL.Real = parseRealNumber(yyDollar[1].Number, 0, yyDollar[3].Number)
		}
	case 117:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:635
		{
			yyVAL.Number = Number(-int(yyDollar[2].Number))
		}
	case 118:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:640
		{
			yyVAL.Type = BitStringType{}
		}
	case 119:
		yyDollar = yyS[yypt-5 : yypt+1]
//line asn1.y:641
		{
			yyVAL.Type = BitStringType{NamedBits: yyDollar[4].NamedBitList}
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:644
		{
			yyVAL.NamedBitList = append(make([]NamedBit, 0), yyDollar[1].NamedBit)
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:645
		{
			yyVAL.NamedBitList = append(yyDollar[1].NamedBitList, yyDollar[3].NamedBit)
		}
	case 122:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:648
		{
			yyVAL.NamedBit = NamedBit{Name: Identifier(yyDollar[1].name), Index: yyDollar[3].Number}
		}
	case 123:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:649
		{
			yyVAL.NamedBit = NamedBit{Name: Identifier(yyDollar[1].name), Index: yyDollar[3].DefinedValue}
		}
	case 124:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:654
		{
			yyVAL.Type = OctetStringType{}
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:659
		{
			yyVAL.Type = NullType{}
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:664
		{
			yyVAL.Type = SequenceType{}
		}
	case 127:
		yyDollar = yyS[yypt-5 : yypt+1]
//line asn1.y:665
		{
			yyVAL.Type = SequenceType{}
		}
	case 128:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:666
		{
			yyVAL.Type = SequenceType{Components: yyDollar[3].ComponentTypeList}
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:708
		{
			yyVAL.ComponentTypeList = append(make(ComponentTypeList, 0), yyDollar[1].ComponentType)
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:709
		{
			yyVAL.ComponentTypeList = append(yyDollar[1].ComponentTypeList, yyDollar[3].ComponentType)
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:712
		{
			yyVAL.ComponentType = NamedComponentType{NamedType: yyDollar[1].NamedType}
		}
	case 148:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:713
		{
			yyVAL.ComponentType = NamedComponentType{NamedType: yyDollar[1].NamedType, IsOptional: true}
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:714
		{
			yyVAL.ComponentType = NamedComponentType{NamedType: yyDollar[1].NamedType, Default: &yyDollar[3].Value}
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:715
		{
			yyVAL.ComponentType = ComponentsOfComponentType{Type: yyDollar[3].Type}
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:720
		{
			yyVAL.Type = SetType{}
		}
	case 152:
		yyDollar = yyS[yypt-5 : yypt+1]
//line asn1.y:721
		{
			yyVAL.Type = SetType{}
		}
	case 153:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:722
		{
			yyVAL.Type = SetType{Components: yyDollar[3].ComponentTypeList}
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:727
		{
			yyVAL.Type = SetOfType{yyDollar[3].Type}
		}
	case 155:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:728
		{
			yyVAL.Type = SetOfType{yyDollar[3].NamedType}
		}
	case 156:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:732
		{
			yyVAL.Type = AnyType{}
		}
	case 157:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:733
		{
			yyVAL.Type = AnyType{Identifier(yyDollar[4].name)}
		}
	case 158:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:738
		{
			yyVAL.Type = yyDollar[3].ChoiceType
		}
	case 159:
		yyDollar = yyS[yypt-5 : yypt+1]
//line asn1.y:741
		{
			yyVAL.ChoiceType = ChoiceType{yyDollar[1].AlternativeTypeList, yyDollar[4].ExtensionAdditionAlternativesList}
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:742
		{
			yyVAL.ChoiceType = ChoiceType{AlternativeTypeList: yyDollar[1].AlternativeTypeList}
		}
	case 162:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:749
		{
			yyVAL.ExtensionAdditionAlternativesList = yyDollar[2].ExtensionAdditionAlternativesList
		}
	case 163:
		yyDollar = yyS[yypt-0 : yypt+1]
//line asn1.y:750
		{
			yyVAL.ExtensionAdditionAlternativesList = make([]ChoiceExtension, 0)
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:753
		{
			yyVAL.ExtensionAdditionAlternativesList = append(make([]ChoiceExtension, 0), yyDollar[1].ExtensionAdditionAlternative)
		}
	case 165:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:754
		{
			yyVAL.ExtensionAdditionAlternativesList = append(yyDollar[1].ExtensionAdditionAlternativesList, yyDollar[3].ExtensionAdditionAlternative)
		}
	case 166:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:758
		{
			yyVAL.ExtensionAdditionAlternative = yyDollar[1].NamedType
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:765
		{
			yyVAL.AlternativeTypeList = append(make([]NamedType, 0), yyDollar[1].NamedType)
		}
	case 169:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:766
		{
			yyVAL.AlternativeTypeList = append(yyDollar[1].AlternativeTypeList, yyDollar[3].NamedType)
		}
	case 170:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:771
		{
			yyVAL.Type = TaggedType{Tag: yyDollar[1].Tag, Type: yyDollar[2].Type}
		}
	case 171:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:772
		{
			yyVAL.Type = TaggedType{Tag: yyDollar[1].Tag, Type: yyDollar[3].Type, TagType: TAGS_IMPLICIT, HasTagType: true}
		}
	case 172:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:773
		{
			yyVAL.Type = TaggedType{Tag: yyDollar[1].Tag, Type: yyDollar[3].Type, TagType: TAGS_EXPLICIT, HasTagType: true}
		}
	case 173:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:776
		{
			yyVAL.Tag = Tag{Class: yyDollar[2].Class, ClassNumber: yyDollar[3].Value}
		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:779
		{
			yyVAL.Value = yyDollar[1].Number
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:780
		{
			yyVAL.Value = yyDollar[1].DefinedValue
		}
	case 176:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:783
		{
			yyVAL.Class = CLASS_UNIVERSAL
		}
	case 177:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:784
		{
			yyVAL.Class = CLASS_APPLICATION
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:785
		{
			yyVAL.Class = CLASS_PRIVATE
		}
	case 179:
		yyDollar = yyS[yypt-0 : yypt+1]
//line asn1.y:786
		{
			yyVAL.Class = CLASS_CONTEXT_SPECIFIC
		}
	case 180:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:791
		{
			yyVAL.Type = SequenceOfType{yyDollar[3].Type}
		}
	case 181:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:792
		{
			yyVAL.Type = SequenceOfType{yyDollar[3].NamedType}
		}
	case 182:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:797
		{
			yyVAL.Type = ObjectIdentifierType{}
		}
	case 183:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:802
		{
			yyVAL.ObjectIdentifierValue = yyDollar[2].ObjectIdentifierValue
		}
	case 184:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:803
		{
			yyVAL.ObjectIdentifierValue = NewObjectIdentifierValue(yyDollar[2].DefinedValue).Append(yyDollar[3].ObjectIdentifierValue...)
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:806
		{
			yyVAL.ObjectIdentifierValue = NewObjectIdentifierValue(yyDollar[1].ObjIdComponents)
		}
	case 186:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:807
		{
			yyVAL.ObjectIdentifierValue = NewObjectIdentifierValue(yyDollar[1].ObjIdComponents).Append(yyDollar[2].ObjectIdentifierValue...)
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:810
		{
			yyVAL.ObjIdComponents = ObjectIdElement{Name: yyDollar[1].name}
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:813
		{
			yyVAL.ObjIdComponents = yyDollar[1].DefinedValue
		}
	case 191:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:816
		{
			yyVAL.ObjIdComponents = ObjectIdElement{Id: yyDollar[1].Number.IntValue()}
		}
	case 192:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:817
		{
			yyVAL.ObjIdComponents = yyDollar[1].DefinedValue
		}
	case 193:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:821
		{
			switch v := yyDollar[3].ObjIdComponents.(type) {
			case DefinedValue:
				yyVAL.ObjIdComponents = ObjectIdElement{Name: yyDollar[1].name, Reference: &v}
			case ObjectIdElement:
				yyVAL.ObjIdComponents = ObjectIdElement{Name: yyDollar[1].name, Id: v.Id}
			default:
				panic(fmt.Sprintf("Expected DefinedValue or ObjectIdElement from NumberForm, got %v", yyDollar[3].ObjIdComponents))
			}
		}
	case 197:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:842
		{
			yyVAL.Type = RestrictedStringType{LexType: BMPString}
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:843
		{
			yyVAL.Type = RestrictedStringType{LexType: GeneralString}
		}
	case 199:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:844
		{
			yyVAL.Type = RestrictedStringType{LexType: GraphicString}
		}
	case 200:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:845
		{
			yyVAL.Type = RestrictedStringType{LexType: IA5String}
		}
	case 201:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:846
		{
			yyVAL.Type = RestrictedStringType{LexType: ISO646String}
		}
	case 202:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:847
		{
			yyVAL.Type = RestrictedStringType{LexType: NumericString}
		}
	case 203:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:848
		{
			yyVAL.Type = RestrictedStringType{LexType: PrintableString}
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:849
		{
			yyVAL.Type = RestrictedStringType{LexType: TeletexString}
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:850
		{
			yyVAL.Type = RestrictedStringType{LexType: T61String}
		}
	case 206:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:851
		{
			yyVAL.Type = RestrictedStringType{LexType: UniversalString}
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:852
		{
			yyVAL.Type = RestrictedStringType{LexType: UTF8String}
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:853
		{
			yyVAL.Type = RestrictedStringType{LexType: VideotexString}
		}
	case 209:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:854
		{
			yyVAL.Type = RestrictedStringType{LexType: VisibleString}
		}
	case 210:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:859
		{
			yyVAL.Type = CharacterStringType{}
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:864
		{
			yyVAL.Type = TypeReference("GeneralizedTime")
		}
	case 212:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:865
		{
			yyVAL.Type = TypeReference("UTCTime")
		}
	case 213:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:870
		{
			yyVAL.Type = ConstraintedType{yyDollar[1].Type, yyDollar[2].Constraint}
		}
	case 215:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:876
		{
			yyVAL.Type = ConstraintedType{SetOfType{yyDollar[4].Type}, yyDollar[2].Constraint}
		}
	case 216:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:877
		{
			yyVAL.Type = ConstraintedType{SetOfType{yyDollar[4].Type}, SingleElementConstraint(yyDollar[2].Elements)}
		}
	case 217:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:878
		{
			yyVAL.Type = ConstraintedType{SequenceOfType{yyDollar[4].Type}, yyDollar[2].Constraint}
		}
	case 218:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:879
		{
			yyVAL.Type = ConstraintedType{SequenceOfType{yyDollar[4].Type}, SingleElementConstraint(yyDollar[2].Elements)}
		}
	case 219:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:880
		{
			yyVAL.Type = ConstraintedType{SetOfType{yyDollar[4].NamedType}, yyDollar[2].Constraint}
		}
	case 220:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:881
		{
			yyVAL.Type = ConstraintedType{SetOfType{yyDollar[4].NamedType}, SingleElementConstraint(yyDollar[2].Elements)}
		}
	case 221:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:882
		{
			yyVAL.Type = ConstraintedType{SequenceOfType{yyDollar[4].NamedType}, yyDollar[2].Constraint}
		}
	case 222:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:883
		{
			yyVAL.Type = ConstraintedType{SequenceOfType{yyDollar[4].NamedType}, SingleElementConstraint(yyDollar[2].Elements)}
		}
	case 223:
		yyDollar = yyS[yypt-4 : yypt+1]
//line asn1.y:888
		{
			yyVAL.Constraint = Constraint{ConstraintSpec: yyDollar[2].ConstraintSpec}
		}
	case 224:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:891
		{
			yyVAL.ConstraintSpec = yyDollar[1].SubtypeConstraint
		}
	case 227:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:901
		{
			yyVAL.SubtypeConstraint = yyDollar[1].SubtypeConstraint
		}
	case 228:
		yyDollar = yyS[yypt-5 : yypt+1]
//line asn1.y:902
		{
			yyVAL.SubtypeConstraint = append(yyDollar[1].SubtypeConstraint, yyDollar[5].ElementSetSpec)
		}
	case 229:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:905
		{
			yyVAL.SubtypeConstraint = SubtypeConstraint{yyDollar[1].ElementSetSpec}
		}
	case 231:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:911
		{
			yyVAL.ElementSetSpec = yyDollar[1].Unions
		}
	case 232:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:912
		{
			yyVAL.ElementSetSpec = yyDollar[2].Exclusions
		}
	case 233:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:915
		{
			yyVAL.Unions = Unions{yyDollar[1].Intersections}
		}
	case 234:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:916
		{
			yyVAL.Unions = append(yyDollar[1].Unions, yyDollar[3].Intersections)
		}
	case 236:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:922
		{
			yyVAL.Intersections = Intersections{yyDollar[1].IntersectionElements}
		}
	case 237:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:923
		{
			yyVAL.Intersections = append(yyDollar[1].Intersections, yyDollar[3].IntersectionElements)
		}
	case 239:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:929
		{
			yyVAL.IntersectionElements = IntersectionElements{Elements: yyDollar[1].Elements}
		}
	case 240:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:930
		{
			yyVAL.IntersectionElements = IntersectionElements{Elements: yyDollar[1].Elements, Exclusions: yyDollar[2].Exclusions}
		}
	case 242:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:936
		{
			yyVAL.Exclusions = Exclusions{yyDollar[2].Elements}
		}
	case 247:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:945
		{
			yyVAL.Elements = yyDollar[1].Elements
		}
	case 248:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:947
		{
			yyVAL.Elements = yyDollar[2].ElementSetSpec
		}
	case 254:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:962
		{
			yyVAL.Elements = SingleValue{yyDollar[1].Value}
		}
	case 255:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:967
		{
			yyVAL.Elements = ValueRange{yyDollar[1].RangeEndpoint, yyDollar[3].RangeEndpoint}
		}
	case 256:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:970
		{
			yyVAL.RangeEndpoint = RangeEndpoint{Value: yyDollar[1].Value}
		}
	case 257:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:971
		{
			yyVAL.RangeEndpoint = RangeEndpoint{Value: yyDollar[1].Value, IsOpen: true}
		}
	case 258:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:974
		{
			yyVAL.RangeEndpoint = RangeEndpoint{Value: yyDollar[1].Value}
		}
	case 259:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:975
		{
			yyVAL.RangeEndpoint = RangeEndpoint{Value: yyDollar[2].Value, IsOpen: true}
		}
	case 261:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:979
		{
			yyVAL.Value = nil
		}
	case 263:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:983
		{
			yyVAL.Value = nil
		}
	case 264:
		yyDollar = yyS[yypt-2 : yypt+1]
//line asn1.y:988
		{
			yyVAL.Elements = SizeConstraint{yyDollar[2].Constraint}
		}
	case 265:
		yyDollar = yyS[yypt-1 : yypt+1]
//line asn1.y:993
		{
			yyVAL.Elements = TypeConstraint{yyDollar[1].Type}
		}
	case 266:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:998
		{
			yyVAL.Elements = InnerTypeConstraint{}
		}
	case 267:
		yyDollar = yyS[yypt-3 : yypt+1]
//line asn1.y:999
		{
			yyVAL.Elements = InnerTypeConstraint{}
		}
	}
	goto yystack /* stack new state and value */
}
